### ISSUE TITLE
Basic expression with operators

### ISSUE THREAD

**Issue by FrMalan** [peteroupc/Numbers#6]
Hi,

Given the code:
```
            var twelve = EDecimal.FromDecimal(12M);
            var e1 = EDecimal.One.Divide(twelve).Multiply(twelve);
            var e4 = EDecimal.One / twelve * twelve;
```
Why is the answer NaN ? I was expecting EDicimal.One
It seems the division is where the NaN comes from.

**Comment by peteroupc** [comment]
EDecimal's Divide method works as documented; see https://peteroupc.github.io/Numbers/docs/PeterO.Numbers.EDecimal.html. It returns NaN "if the result can't be exact because it would have a nonterminating decimal expansion" (as is the case for 1 divided by 12).

In general, the Divide method and the EDecimal division operator return an exact result when possible, or NaN if that is not possible.

**Comment by FrMalan** [comment]
That makes sense, thank you for the explanation and link to the docs.
