### ISSUE TITLE
1 / 0.14 is NaN?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [peteroupc/Numbers#8]
```cs
EDecimal a = 0.14m;
EDecimal b = 1.0m;
Console.WriteLine(b / a);
```
Results in
```
NaN
```
(division by 0.1 and 0.2 is fine though)

I assume there's a default context I need to set?

**Comment by peteroupc** [comment]
See #3.

EDecimal's "operator /" works as documented; see https://peteroupc.github.io/Numbers/docs/PeterO.Numbers.EDecimal.html.  It returns NaN "if the result can't be exact because it would have a nonterminating decimal expansion" (as is the case for 1 divided by 3); moreover, NaN isn't a finite number.

**Comment by WhiteBlackGoose** [comment]
I see. Is there a way to make it fill the rest of the precision-length mantissa with the period, or I should use EFloat instead?

**Comment by peteroupc** [comment]
What do you mean?

**Comment by peteroupc** [comment]
You will have to use a suitable EDecimal method instead of the division operator.  An example is DivideToExponent, or a Divide overload that takes an EContext.

**Comment by WhiteBlackGoose** [comment]
Alright, thank you
